### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/guardian#1]
## Purpose:

CLI tool & JS library to monitor for unsafe positions, and execute a script when criteria are met. The script can notify users, or initiate/participate in actions such as send a transaction.

## Use cases

- For operator
  - Power dashboard to monitor for various status such as TPS, transaction volume, etc
  - Perform sanity checks to ensure data consistency
- For user
  - Monitor account balance changes
  - Acala
    - Monitor CDP collateral ratio
  - Laminar
    - Monitor margin level
    - Monitor margin position profit / lost
- For arbitrageur
  - Acala
    - Monitor DEX price
    - Monitor auctions
  - Laminar
    - Monitor synthetic pool liquidations
- For exchange / merchant
  - Monitor incoming transactions
  - Monitor unexpected transactions
- For laminar liquidity pool provider
  - Synthetic pool
    - Monitor collateral ratio
    - Various status for dashboard
  - Margin pool
    - Monitor ENP & ELL
    - Various status for dashboard

### CLI:

```bash
guardian ./path/to/config.yml
```

### JS:

```js
import guardian from '@open-web3/guardian'

const config = // ...
guardian(config)
```

### Config file:

YAML file with `lodash.template` for environment variable interpolation. Use `${ VALUE }` syntax.

Something like

```js
const yamlFileString = _.template(yamlFileString)(process.env)
const config = YAML.parse(yamlFileString)
```

Example Config:

```yaml
version: "0.1" # for compatibility check, for now, error exit on any other value
guardians: # mapping of guardians
  lamianr-chain: # user defined name
    networkType: laminarChain # laminarChain | ethereum
    network: dev # dev | turbulence | reynolds | mainnet
    nodeEndpoint: ws://localhost:9944 # Endpoint URL. Optional. If not specified, use our hosted node.
    confirmation: finalize # 'finalize' | number. Optional, default to 0, means no confimation required and up to action handler to handle forks.
    actionParameters: # additional values to be passed to action handlers
    	- networkType
    	- network
    	- blockNumber
    	- blockHash
    monitors: # mapping of monitors to run
      synthetic-pool: # user defined name
        task: synthetic.liquidityPool # see tasks
        arguments:
          poolId: all
          currencyId:
            - FEUR
            - FJPY
            - FBTC
        conditions: # trigger action if any of the conditions are true. this is optional, if omitted, action always get triggered when value changed
          - collateralRatio: < 1.1 # custom number parser, see below
          - $and: # and gate
            - $or: # or gate
              - currencyId: FEUR # access input variable
              - currencyId: FJPY
            - collateralRatio: < 120% # equivalent to 1.2
        actions:
          - method: POST # POST | script
            url: http://localhost:8080 # arguments are passed via body using json format
            headers: # optional additional headers
              - X-API-KEY: ${API_KEY}
          - method: script # arguments are piped to stdin as a json string
            path: ./notify.sh
      margin: # user defined name
        task: margin.poolInfo
        arguments:
          poolId: 1
        conditions:
          - enp: < 60%
          - ell: < 80%
        actions:
          - method: script
            path: ./topup.js
      new-position:
      	task: system.events
      	arguments:
      		name: marginProtocol.PositionOpened
      	conditions:
      		- 2: ${MY_POOL_ID} # check args by index
      		- who: ${MY_ADDRESS} # check args by name
    
  flow-ethereum: # another user defined name
    networkType: ethereum
    network: dev # dev | kovan | mainnet
    nodeEndpoint: wss://kovan.infura.io/ws/v3/${INFRA_API_KEY} # Endpoint URL. Required except for dev, which default to http://localhost:8545
  
  
```

Custom number parser:

Regex: `^\s*(?<op>=|!=|<|<=|>|>=)\s*(?<val>\$?\s*-?\s*\d[\d_\s]*(\.[\d\s]+)?\s*%?)\s*$`

https://regex101.com/r/deUUe0/1

### Tasks:

See #3 #6 #7 #8 #9 #10 #11 #12
